### ISSUE TITLE
open default with sublime doesn't seem to work

### ISSUE THREAD

**Issue by ohadperry** [BetterErrors/better_errors#100]
istall this gem, 
configured like so:

configure :development do
  use BetterErrors::Middleware
  BetterErrors.application_root = File.expand_path("..", **FILE**)
end

BetterErrors.editor = :subl if defined? BetterErrors

but it's not working. default text mate works.

**Comment by fabriciofreitag** [comment]
installing this was enough for me: https://github.com/rubysamurai/sublime-url-handler
