### ISSUE TITLE
Reload code and continue execution

### ISSUE THREAD

**Issue by augnustin** [BetterErrors/better_errors#242]
Hey,

This gem is pure gold. It is amazing, I could not imagine working without it.

I want to suggest a feature that would be super nice, though I'm not even sure it is technically possible. 

Basically, the idea would be to consider errors (exceptions) as breakpoints and by typing something in the better error live console (eg. `continue`) it reloads the file content (as the error was debugged) and continues its execution.

It would make debugging even faster that it already is with better error!

Thanks for comments and replies.

**Comment by jekuno** [comment]
Maybe it would make sense to clarify this point in the Readme and also reference the 'web-console' gem and 'pry-byebug' gem there.
