### ISSUE TITLE
TypeError - no _dump_data is defined for class Binding:

### ISSUE THREAD

**Issue by yogendra689** [BetterErrors/better_errors#254]
I m getting one issue when marshalling data in rails application.
We are using active_record_store for caching:

<pre>
Sample::Application.config.session_store :active_record_store
</pre>

its giving this error:

<pre> TypeError - no _dump_data is defined for class Binding:
  config/initializers/active_record.rb:4:in `marshal'
  activerecord (3.2.18) lib/active_record/session_store.rb:150:in `marshal_data!'
  activesupport (3.2.18) lib/active_support/callbacks.rb:407:in `_run__343736847__save__402356227__callbacks'
  activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.18) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
  activesupport (3.2.18) lib/active_support/callbacks.rb:81:in `run_callbacks'
  activerecord (3.2.18) lib/active_record/callbacks.rb:264:in `create_or_update'
  activerecord (3.2.18) lib/active_record/persistence.rb:84:in `save'
  activerecord (3.2.18) lib/active_record/validations.rb:50:in `save'
  activerecord (3.2.18) lib/active_record/attribute_methods/dirty.rb:22:in `save'
  activerecord (3.2.18) lib/active_record/transactions.rb:259:in `block (2 levels) in save'
  activerecord (3.2.18) lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
  activerecord (3.2.18) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  activerecord (3.2.18) lib/active_record/transactions.rb:208:in `transaction'
  newrelic_rpm (3.8.1.221) lib/new_relic/agent/method_tracer.rb:497:in `block in transaction_with_trace_ActiveRecord_self_name_transaction'
  newrelic_rpm (3.8.1.221) lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
  newrelic_rpm (3.8.1.221) lib/new_relic/agent/method_tracer.rb:493:in `transaction_with_trace_ActiveRecord_self_name_transaction'
  activerecord (3.2.18) lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
  activerecord (3.2.18) lib/active_record/transactions.rb:259:in `block in save'
  activerecord (3.2.18) lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
  activerecord (3.2.18) lib/active_record/transactions.rb:258:in `save'
  activerecord (3.2.18) lib/active_record/session_store.rb:323:in `block in set_session'
  activesupport (3.2.18) lib/active_support/benchmarkable.rb:50:in `silence'
  activerecord (3.2.18) lib/active_record/session_store.rb:320:in `set_session'
  rack (1.4.5) lib/rack/session/abstract/id.rb:327:in `commit_session'
  rack (1.4.5) lib/rack/session/abstract/id.rb:211:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.18) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.18) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `_run__345051598__call__402356227__callbacks'
  activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.18) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.18) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.18) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.18) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.18) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.18) lib/rails/rack/logger.rb:16:in `call'
  quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  actionpack (3.2.18) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.18) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.18) lib/rails/engine.rb:484:in `call'
  railties (3.2.18) lib/rails/application.rb:231:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.18) lib/rails/rack/log_tailer.rb:17:in `call'
  thin (1.6.2) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.2) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.2) lib/thin/connection.rb:53:in `process'
  thin (1.6.2) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.2) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.2) lib/thin/server.rb:162:in `start'
  rack (1.4.5) lib/rack/handler/thin.rb:13:in `run'
  rack (1.4.5) lib/rack/server.rb:268:in `start'
  railties (3.2.18) lib/rails/commands/server.rb:70:in `start'
  railties (3.2.18) lib/rails/commands.rb:55:in `block in <top (required)>'
  railties (3.2.18) lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:6:in `<main>'
  script/rails:0:in `<main>'
</pre>

After debugging i see in data before marshalling it adds something like binding trace,

data in yaml form:

<pre>
--- !ruby/exception:Ty \nmessage: Invalid number\n__better_errors_bindings_stack: \n- !ruby/object:Binding \n  frame_description: get_partner_rfc_output\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: execute\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: get_one\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: get_pat\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: manual_entry\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: populate_prerequisites\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: populate_prerequisites\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: shop\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: send_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in process_action\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: _run__816577052__process_action__906960469__callbacks\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: __run_callback\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: _run_process_action_callbacks\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: run_callbacks\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in process_action\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: block in instrument\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: instrument\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: instrument\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in process_action\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: perform_action_with_newrelic_trace\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process_action\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: dispatch\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: dispatch\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in action\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: dispatch\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in call\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: context\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in call\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: _run__913420421__call__417485616__callbacks\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: __run_callback\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: _run_call_callbacks\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: run_callbacks\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: protected_app_call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: better_errors_call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call_app\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in call\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: tagged\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call_with_quiet_assets\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: call\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in pre_process\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: pre_process\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: process\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: receive_data\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: run\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: start\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: start\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: run\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: start\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: start\n  frame_type: :method\n- !ruby/object:Binding \n  frame_description: block in <top (required)>\n  frame_type: :block\n- !ruby/object:Binding \n  frame_description: <top (required)>\n  frame_type: :top\n- !ruby/object:Binding \n  frame_description: <main>\n  frame_type: :eval\n- !ruby/object:Binding \n  frame_description: <main>\n  frame_type: :top\nid 453626456
</pre>

Unable to figure out why "!ruby/object:Binding \n  frame_description: start\n  frame_type: :method" is getting in the data.

thanks for this awesome gem.

**Comment by ndbroadbent** [comment]
Hi @charliesome - I ran into this issue while working on the `parallel` gem for parallel processing, since `parallel` uses exceptions to kill or break the workers. I've sent them a PR with a workaround (https://github.com/grosser/parallel/pull/202), but would it also be easy to fix this in better errors? Maybe just strip away the binding stuff and marshall the original exception?

_(I'm testing on the latest version of better_errors: 2.1.1)._
