### ISSUE TITLE
better_errors not working in a Docker container

### ISSUE THREAD

**Issue by zedtux** [BetterErrors/better_errors#270]
Hello,

I'm opening this issue in order to try to figure out why the fact that my app is in a Docker container it makes better_errors not shown.

Quick summary: I have start to build a Rails 4.x application on my Mac. Everything is working just perfectly.
Then I have the task to containerise my application in order to work with other developers and also deploy in test etc...
The application is working properly excepted that better_errors is not running. I'm having the standard Rails error page.

What shall I check in order to understand the issue ?

Thank you in advance.

**Comment by aug-riedinger** [comment]
Same issue here, except I'm not using boot2docker (under linux) and visiting http://localhost:3000 still.
I tried `BetterErrors::Middleware.allow_ip! '0.0.0.0'`, without success

**Comment by gfauredumont** [comment]
@aug-riedinger don't know if you got a permanent solution...
I don't have time for this so, for now, I just run a request on my rails container, getting the served IP in the logs (something like `Started GET "/community/index" for 172.17.42.1 at 2015-08-27`), I can use this IP in the config file and restart my container (unlike Vagrant, restarting Docker components is lightning fast !!)

**Comment by sullyme** [comment]
Any news about this? With last Docker it doesn't work.

**Comment by cpapidas** [comment]
1. Create the file **config/initializers/better_errors.rb**
2. Add the follow line `BetterErrors::Middleware.allow_ip! "0.0.0.0/0"`
3. restart your server 

if you have still troubles try to start your server with **rails s -p 3000 -b '0.0.0.0'**

**Comment by exadeci** [comment]
@cpapidas You basically open your Better Errors console for the world to use if you do it this way.
Your line is fine as long as it's inserted in `config/environements/development.rb`

**Comment by aug-riedinger** [comment]
@cpapidas solution worked for me, but please don't forget:

```
if Rails.env.development?
    BetterErrors::Middleware.allow_ip! '0.0.0.0/0'
end
```
if you installed better error in development environment only:
```
group :development do
  gem 'better_errors'
end
```
otherwise it will fail when pushing to prod.
