### ISSUE TITLE
Remove rails stack trace?

### ISSUE THREAD

**Issue by danlo** [BetterErrors/better_errors#281]
Greetings,

Is there some method by which I can remove the Rails centric parts of the stack trace and only show "my" application parts?

-daniel

**Comment by RobinDaugherty** [comment]
Sorry this sat unanswered for so long. When you're looking at a backtrace, if Application Frames has a strikethrough, that means that there are no non-gem frames in the backtrace. This is usually the result of Rails executing actions that are declared in models or controllers, such as validations or other callbacks. There are actually no lines of application code in the backtrace, so it can be very difficult to troubleshoot these issues.
