### ISSUE TITLE
Session expired with Rails 4.1 on Thin

### ISSUE THREAD

**Issue by joallard** [BetterErrors/better_errors#292]
I don't really know how to debug this, any pointers?

**Comment by joallard** [comment]
It's pretty critical, can I get some help?

**Comment by rmm5t** [comment]
Just to confirm, are you running just a single thin server (aka process)?

```
ps -ef | grep thin 
```

**Comment by joallard** [comment]
Not much seems interesting 

```
$ ps -ef | grep thin
    0   262     1   0  9Dec14 ??         0:00.02 /usr/libexec/discoveryd_helper --loglevel Detailed --logclass Everything --logto asl
   65 72395     1   0  1Jan15 ??         3:27.57 /usr/libexec/discoveryd --udsocket standard --loglevel Basic --logclass Everything --logto asl
  501 52760   612   0 11:46am ttys000    0:00.01 grep thin
$ ps -ef | grep rails
  501  5461  5459   0 Mon05pm ??         0:08.54 rails_console
  501 52773   612   0 11:46am ttys000    0:00.01 grep rails
  501 52716   984   0 11:45am ttys001    0:08.43 ruby bin/rails s -p 5000
---
$ bin/rails s -p 5000
=> Booting Thin
=> Rails 4.1.8 application starting in development on http://0.0.0.0:5000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:5000, CTRL+C to stop
```

**Comment by brandonsturgeon** [comment]
I'm on 4.0, but I'm also having this issue. Server is single worker and we're still getting Session Expired on the error pages.

**Comment by KyleMacey** [comment]
Also getting this now

**Comment by ThomasLamiraud** [comment]
Also getting this error usin Thin web server (v1.6.3 codename Protein Powder), Rails 4.1.6, chromium

**Comment by Quintasan** [comment]
I'm getting the same thing here though I'm using Sinatra 1.4.6 and Thin 1.6.3. The issue triggers when starting the application via `rackup`. When I start it using `thin start` it works flawlessly.

**Comment by bornabr** [comment]
I'm getting this now.

**Comment by RobinDaugherty** [comment]
thin can be used as a multithreaded server. The default is to run in single-threaded mode, but if you configure thin (or any rack server) to run the rails app with multiple threads, you will get "session expired" in Better Errors.

I've added documentation about this to the wiki: https://github.com/BetterErrors/better_errors/wiki/Multithreaded-servers-in-development
