### ISSUE TITLE
better_errors should show Exception#cause when present

### ISSUE THREAD

**Issue by gioele** [BetterErrors/better_errors#296]
When `better_errors` shows an unhandled exception, it should show also the cause exception returned by `Exception#cause`.

`Exception#cause` is set automatically since Ruby 2.1, see http://devblog.avdi.org/2013/12/25/exception-causes-in-ruby-2-1/.

**Comment by RobinDaugherty** [comment]
The current version of better_errors actually shows the cause of the exception being shown, if there is one. However, it does this by blindly folding the top level exception and instead displaying its `cause`. If there is more than two layers of exceptions, it does not show the original exception.

It could display the full stack of exceptions rather than just choosing one exception to display.

**Comment by sj26** [comment]
This seems to be a big issue. Take the following snippet of code:

```ruby
begin
  raise StandardError.new("OMG the world broke!")
rescue StandardError => e
  raise StandardError.new("The real slim shady is: #{e.inspect}")
end
```

When raised in a controller this shows better errors as follows:

![screen shot 2018-01-23 at 1 04 54 pm](https://user-images.githubusercontent.com/14028/35254388-12f73854-003e-11e8-8f4a-5bf44013b464.png)

This is very misleading.

Native rails shows:

![screen shot 2018-01-23 at 1 05 42 pm](https://user-images.githubusercontent.com/14028/35254403-298c17e2-003e-11e8-87b2-34ff20057b18.png)

If the inner exception is expected and handled, but subsequent handling code fails and I need to diagnose and fix the handler then this is going to make things much harder.

imho better_errors should be showing the top-level exception, then allow digging into cause exceptions if neccessary.

**Comment by RobinDaugherty** [comment]
I'm not sure why the default is to show only the cause of the most-recently-raised exception. It was done in https://github.com/charliesome/better_errors/commit/a3edf53600c69dea9792edd5cab3d70e9f99a8cc but I don't think it was intentional to make it apply to all exceptions like it does. I think changing this to a configurable list of exception types would be best, so that `ActionView::Template::Error` can be done by default, and more can be added where it makes sense.

**Comment by sj26** [comment]
Ah, a3edf53600c69dea9792edd5cab3d70e9f99a8cc looks like it pre-dates ruby's `Exception#cause`, when only a handful of rails exceptions had an `#original_exception`, and for that handful (like `ActionView::Template::Error`) looking at the underlying exception would make sense.

But times have changed, and `#original_exception` now seems to also apply to anything with a `#cause`, so, as you say, having a whitelist makes more sense. Or providing a way to navigate into the stack of `#cause` exceptions generically.

**Comment by stevecrozz** [comment]
Our team is also running into this. It seems it would be ideal to show the whole chain of errors with all of the underlying causes. But I'd settle for the rails default behavior where only the highest level exception is shown. Is there agreement on this? Would a pull request makes this change be accepted?

**Comment by mikeahmarani** [comment]
@sj26 Did you ever resolve this? I'm running into the exact same problem.

**Comment by tylerhunt** [comment]
This just bit me as well. Discarding the top-level exception really doesn't make any sense, and this issue caused me a good deal of wasted time today.

I think @sj26 hit the nail on the head with https://github.com/charliesome/better_errors/issues/296#issuecomment-364283953; the `#original_exception` check was probably helpful in older Rails apps for showing the more useful source of the exception, but doing this blindly for all errors using `#cause` is problematic.

@charliesome @RobinDaugherty Until a better solution (possibly involving navigation of the exception hierarchy) can be implemented, could we roll back #354 and just use the error as-is unless an `#original_exception` is defined?

**Comment by stevecrozz** [comment]
@charliesome Would you merge a PR that stops replacing `exception` with `exception.cause`?

**Comment by MGPalmer** [comment]
Yeah same here, just wasted half an hour looking at the same original exception and starting to doubt my sanity oO

**Comment by sj26** [comment]
Amazing!

**Comment by MGPalmer** [comment]
Great!
