### ISSUE TITLE
“This is a live shell. Type in here.” gets old *really* fast.

### ISSUE THREAD

**Issue by alminde** [BetterErrors/better_errors#315]
We know it’s live already. No need to tell us.

Granted, this is nitpicking, but it would a lot cleaner without that message. Please? :grin:

Apart from that little detail, I absolutely love this gem. Great job, guys!

**Comment by rstacruz** [comment]
on that note, it may be a good time to revisit the design entirely. @charliesome?

**Comment by lacostenycoder** [comment]
@alminde you could literally fix that in 30 seconds.
clone gem.  find and remove or comment out these 3 lines of htmel code in variable_info.erb in templates.
either push to your own repo and use that in your gemfile.
Done.

```
    <div class="hint">
        This is a live shell. Type in here.
    </div>

```

**Comment by alminde** [comment]
Yeah, @lacostenycoder. Thanks.

In fact I already did but just forgot to make a pull request.

**Comment by RobinDaugherty** [comment]
I'm pretty sure the solution here is to remove the "helpful prompt" after the REPL has been used, rather than removing it forever. This could even be stored in a cookie or local storage so that the prompt isn't shown to the same developer twice (on the same project at least).
