### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by rking** [BetterErrors/better_errors#36]
To further adoption (and to prevent it from being really profitable to spider port 3000 looking for better_error's), what kinds of ideas can we come up with for security?

I'd be OK with a very simple layer, such as you have to type in a user-configured password (just a few chars) to open the REPL. If done right, it could be remembered by the browser and thus provide very little irritation for good users, while still thwarting simple attack spiders.

A more complete solution could go further.

http://www.youtube.com/watch?v=jZkdcYlOn5M#t=1m31s

**Comment by bicepsarda** [comment]
Helal beyler ne kadarda yardimlasmissiniz aferin boyle olmasi gerek. Kod yazarken bencil olmicaksin empati kurcaksin. Bu meslekte insanlik isleyen koddan daha onemli.
