### ISSUE TITLE
Secure use over the internet

### ISSUE THREAD

**Issue by wnewbery** [BetterErrors/better_errors#392]
It would be really nice if there were built in features to use this securely when there is an issue on a remote host easily (e.g. without using a VPN or such), assuming of course the site is running HTTPS already.

IP checking can be difficult to manage for remote use (various different internet access points, and often many users, many untrusted share a public IP). And while it would seem possible to restrict access to `/__better_errors/` via other configuration (e.g. basic auth), the initial page still contains a lot of information it would be nice to hide.

Has there been any thought on the possibility, or any existing "hooks" to make this secure? e.g. the ability to use other checks in addition to IP  (for example perhaps allow sites to add a special secure cookie to bypass the IP check and gain access, or check an attribute for the logged in user)?

**Comment by JackWetson** [comment]
I think this gives a pretty concise overview about the security risks you might be opening yourself up to, as well as possible alternatives

https://github.com/BetterErrors/better_errors/issues/436#issuecomment-463663556
