### ISSUE TITLE
Opens New VS Code Welcome Page in New Window

### ISSUE THREAD

**Issue by richjdsmith** [BetterErrors/better_errors#428]
I have added the below lines to my .zshrc, but when I click on a link to the source code, it opens a new instance/window of VS Code, and doesn't actually open the file - just the welcome page for VS Code. 

```
export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export EDITOR="code"
```

Any suggestions? Is this just me or a common problem? If so, I'll dig around and try and submit a PR.

**Comment by RobinDaugherty** [comment]
What OS are you using? Which browser and which version of VSCode?

I can confirm that on macOS 10.13.6, Safari and Chrome 68, and VSCode 1.27.2.

**Comment by bicepsarda** [comment]
Abi cok iyi kod ya bakiyorum bakiyorum bu ne ya diyorum mr.robot gibisin helal olsun

**Comment by richjdsmith** [comment]
macOS 10.12.6, Firefox 64, and VSCode 1.28.2

**Comment by RobinDaugherty** [comment]
Sorry for the delayed response.

Did you follow the instructions to install the Shell Command? You should not modify your `PATH`, VSCode will place the shell command `/usr/local/bin/code` which should already be in your `PATH`. _If you have a previous version of the Shell Command installed, it will be earlier in your `PATH` and will therefore take precedence over the one in the app bundler that you place in the `PATH`._

I can confirm that with macOS 10.14.1, Firefox 63.0.3 (the current release), and VSCode 1.29.1, the correct line and file are opened using the link, in the existing project window.

**Comment by andrewcupper** [comment]
I got this to work with VS code by editing config/initializers/better_errors.rb as follows: 

```
if defined?(BetterErrors)
   BetterErrors.editor = proc { |file, line| 'vscode://file%{file}:%{line}' % { file: file, line: line } }
end
```
