### ISSUE TITLE
Not compatible with Pow?

### ISSUE THREAD

**Issue by jviney** [BetterErrors/better_errors#44]
Just tried out this fabulous gem!

Unfortunately it doesn't seem to work nicely with pow.

![better-errors-pow](https://f.cloud.github.com/assets/7051/7645/6c03f500-4431-11e2-80e6-ce5b9f34c0c4.png)

Works fine if I launch the app with unicorn instead.

**Comment by RobinDaugherty** [comment]
There's a temporary patch for Pow here: https://gist.github.com/RobinDaugherty/2731f20d303e6506d451384df2189210

If you update or reinstall Pow, you'll have to re-apply this patch. Hopefully https://github.com/josh/nack/pull/42 will get merged and released.
