### ISSUE TITLE
BetterErrors::Middleware.allow_ip! being ignored

### ISSUE THREAD

**Issue by JackWetson** [BetterErrors/better_errors#442]
Ruby: 2.6.3
Rails: 6.0.0.rc2

I define BetterErrors::Middleware.allow_ip! "0.0.0.0/0" in config/development.rb (I did have a smaller scope but for the sake of testing). Yet better errors appear to ignore this:

`Cannot render console from 10.10.1.103! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255`

**Comment by JackWetson** [comment]
Turns out I had config.consider_all_requests_local = false set.

This needed to be config.consider_all_requests_local = true

**Comment by RobinDaugherty** [comment]
Thanks @JackWetson I've updated [the documentation](https://github.com/BetterErrors/better_errors/wiki/Allowing-access-to-the-console) to reflect that `consider_requests_local` must be enabled.
