### ISSUE TITLE
Question: Any plan to support ActionableError?

### ISSUE THREAD

**Issue by olimart** [BetterErrors/better_errors#443]
Hi,
Any plan to support Actionable Errors released with Rails 6?

**Comment by ethan-dowler** [comment]
I came here to ask this question, but it looks like it's already been asked.

**Comment by RobinDaugherty** [comment]
This is a great idea. I've added it to the roadmap. Pull requests welcome!

**Comment by connorshea** [comment]
I've opened a PR for this :)
