### ISSUE TITLE
uninitialized constant ActionView::Template::SyntaxErrorInTemplate Did you mean?  ActionView::SyntaxErrorInTemplate

### ISSUE THREAD

**Issue by ccasabona** [BetterErrors/better_errors#445]
In a rails 6 app, upon entering this code in an erb view template: 

`<%= if @user.errors.any? %>

<% end %>`

Rails returns

uninitialized constant ActionView::Template::SyntaxErrorInTemplate
Did you mean?  ActionView::SyntaxErrorInTemplate

Note the = sign in the conditional.

Without better_errors installed, Rails returns the correct error message:

ActionView::SyntaxErrorInTemplate in ...

**Comment by ansonhoyt** [comment]
I ran into this as well, and found https://github.com/rails/rails/issues/37512. Mentioning it to help people find their way here. Thanks for reporting!

**Comment by RobinDaugherty** [comment]
Looks like the fix was made to Rails. If anyone sees this bug again, please let us know.
