### ISSUE TITLE
running better_errors without rails

### ISSUE THREAD

**Issue by tansaku** [BetterErrors/better_errors#447]
Apologies if this is the wrong place to ask, but I love the feature of getting a console to inspect what's going on when there's been an error.

Is there any way to get that feature of better_errors outside the rails stack, e.g. when just running in ruby so that an error or exception takes one to a debug console?

**Comment by RobinDaugherty** [comment]
Better Errors is a Rack middleware, it doesn't require Rails though some functionality differs when Rails is in use. More information about other frameworks is provided [in the wiki](https://github.com/BetterErrors/better_errors/wiki/Non-Rails-frameworks).
