### ISSUE TITLE
Add `Run pending migrations` button

### ISSUE THREAD

**Issue by elalemanyo** [BetterErrors/better_errors#455]
Rails 6 added ActiveSupport::ActionableError module to define actions we want perform on errors, right from the error page.
PendingMigrationError added by default a button that says Run pending migrations. Clicking on this button would dispatch rails db:migrate action. Page will reload once migrations run successfully.
Would be great to have this button also when we use better_errors.

**Comment by RobinDaugherty** [comment]
This is a duplicate of #443. A great idea, but nobody has had the time to implement it yet.
