### ISSUE TITLE
Add copy path button

### ISSUE THREAD

**Issue by elalemanyo** [BetterErrors/better_errors#460]
Maybe is just me but a button to copy the path would be nice, something like GitHub do:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/3856862/80493561-dc5ce880-8965-11ea-801e-bc44e4162888.png">

<img width="432" alt="image" src="https://user-images.githubusercontent.com/3856862/80494784-60fc3680-8967-11ea-9346-9eadcde55c01.png">

Thanks for this amazing gem!

**Comment by RobinDaugherty** [comment]
@elalemanyo that's interesting, but can you say more? Would you be looking for the full path, or relative to the project root? What would you be using this for? Did you know that there's an editor link built in that is customized to work with your editor?

**Comment by elalemanyo** [comment]
@RobinDaugherty I am looking for the project root so I can search it on my editor, I saw the link but is not working on my editor 😞

**Comment by RobinDaugherty** [comment]
@elalemanyo [the editor link is customizable](https://github.com/BetterErrors/better_errors/wiki/Link-to-your-editor) and is set based on your `EDITOR` environment variable.

**Comment by elalemanyo** [comment]
@RobinDaugherty 🙈 sorry I didn't saw that. I set my EDITOR and now works even better as I wanted to, now opens directly where I need to fix something 😊
Thanks for all your help and for the great gem!
