### ISSUE TITLE
When ActionView::Template::Error is shown, live shell is missing on last frame

### ISSUE THREAD

**Issue by RobinDaugherty** [BetterErrors/better_errors#466]
The synthesized frame doesn't have a binding, so there's no live shell for it. There is a binding that could be used for this frame, but it's in the `cause`'s top stack frame, not deeper in the most recent (topmost) error's stack frame.

One solution is to show the `cause` of the `ActionView::Template::Error` instead of synthesizing a backtrace frame. That would be a quick fix, but has the disadvantage that there might be useful debug information in the topmost error.

#464 would solve this while allowing the developer to navigate between the causes instead of only showing a specific one. A nice-to-have in that case would be for Better Errors to show the second cause in the chain by default, while still allowing navigation back to the `ActionView::Template::Error`.

**Comment by aximuseng** [comment]
Same issue here - I have a partial rendered and can't inspect anything on that page to find the nil error I am getting.

**Comment by skatkov** [comment]
We rolled back to 2.5.1 version and this bug disappeared.
