### ISSUE TITLE
Release 2.8.2

### ISSUE THREAD

**Issue by manuelmeurer** [BetterErrors/better_errors#479]
It seems like v2.8.2 was not tagged on Github and released to Rubygems yet.
I am eagerly waiting for it because of the included fix to the cookie path! 😸

**Comment by peaonunes** [comment]
> It seems like v2.8.2 was not tagged on Github and released to Rubygems yet.
> I am eagerly waiting for it because of the included fix to the cookie path! 😸

According to https://rubygems.org/gems/better_errors/versions/2.8.2 it is there.
However after upgrading it I got `NameError: uninitialized constant BetterErrors::Middleware::VERSION`, I'm not sure if that's related though.

**Comment by ryanb** [comment]
I am receiving the `NameError: uninitialized constant BetterErrors::Middleware::VERSION` error as well. I recommend holding off on upgrading until it is fixed.

**Comment by thebravoman** [comment]
I also also got the error after update

``` 
-    better_errors (2.7.1)
+    better_errors (2.8.2)
```

**Comment by manuelmeurer** [comment]
#481 should fix this.
