### ISSUE TITLE
uninitialized constant BetterErrors::Middleware::VERSION (NameError)

### ISSUE THREAD

**Issue by seb-sykio** [BetterErrors/better_errors#483]
3: from .rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors.rb:9:in `<top (required)>'
	 2: from .rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:7:in `<top (required)>'
	 1: from .rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:28:in `<module:BetterErrors>'
.rvm/gems/ruby-2.6.5/gems/better_errors-2.8.2/lib/better_errors/middleware.rb:43:in `<class:Middleware>': uninitialized constant BetterErrors::Middleware::VERSION (NameError)

ruby 2.6
rails 4.2.11.3

**Comment by frobert** [comment]
Same here after update :/

**Comment by joker-777** [comment]
Same for me!

**Comment by frobert** [comment]
Duplicate of https://github.com/BetterErrors/better_errors/issues/482

**Comment by afuno** [comment]
Same

**Comment by jcoglan** [comment]
I believe this change is the source of the problem: referring to `VERSION` without having explicitly loaded that constant. It's stopping our Rails app from booting.

https://github.com/BetterErrors/better_errors/compare/v2.8.1..master#diff-5e3c1d57ea649185a86b730f951f5a18R43

**Comment by addisonmartin** [comment]
I've submitted a fix:
https://github.com/BetterErrors/better_errors/pull/480

**Comment by RobinDaugherty** [comment]
Very sorry for my mistake everyone, release 2.8.3 fixes this and is live (and I tested it in an app). Thank you @addisonmartin and @peaonunes for the PRs!
