### ISSUE TITLE
Auto-inspecting ActiveRecord::Relation hangs the server

### ISSUE THREAD

**Issue by jdelStrother** [BetterErrors/better_errors#72]
Hi there - I've been having problems with better_error auto-inspecting instance variables, when one of those ivars is an ActiveRecord::Relation.  It basically hangs my server until unicorn gets impatient and kills the connection.

In my case, I had a model with a custom table_name, which results in the class object having an @relation instance variable which would attempt to load the entire table (a few million rows) into memory : 

``` ruby
class Foo
   self.table_name = 'bars'   # gives an @relation class ivar
   def self.do_something
      raise "FFUUU"     # causes better_errors to try call @relation.inspect via ErrorPage#inspect_value
   end
end
```

Any thoughts on the best work around?  Rails 4 no longer loads the entire result set on `#inspect` - see https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L552.  It's tempting to backport it....

**Comment by amiryal** [comment]
To anyone still bugged by this, I could not find the Rails 4 fix @charliesome was referring to – the latest code in `rails/rails@master` still calls `.to_a` on the relation – so I did the following:

```ruby
class ActiveRecord::Relation
  # Stop it from doing a SELECT * FROM
  #
  # Backported and adapted from
  # https://github.com/rails/rails/blob/591a0bb87fff7583e01156696fbbf929d48d3e54/activerecord/lib/active_record/relation.rb#L659
  #
  # TODO: send patch to Rails
  def inspect
    entries = limit([limit_value, 11].compact.min).to_a.map!(&:inspect)
    entries[10] = '...' if entries.size == 11

    "#<#{self.class.name} [#{entries.join(', ')}]>"
  end
end
````
